version: '3.5'

services:

  logstash:
    build:
      context: logstash/
    ports:
      - 5000:5000
      - 5043:5043
      - 12201:12201/udp
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      LOGANALYTICS_CLIENT_ID: $LOGANALYTICS_CLIENT_ID
      LOGANALYTICS_CLIENT_SECRET: $LOGANALYTICS_CLIENT_SECRET
      LOGANALYTICS_INDEX: $LOGANALYTICS_INDEX
      APPINSIGHTS_INSTRUMENTATION_KEY: $APPINSIGHTS_INSTRUMENTATION_KEY
    networks:
      - logging

  # test:
  #   build:
  #     context: test/
  #   ports:
  #     - 5045:5045
  #   logging:
  #     driver: gelf
  #     options:
  #       gelf-address: "udp://192.168.99.100:12201"
  #   networks:
  #     - logging
  #   depends_on:
  #     - logstash

networks:
  logging:
