{
 "title": "Container Runtime",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "last",
    "label": "last",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$last])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Input",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Network Output",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}