{
 "title": "Container Host",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "last",
    "label": "last",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum by (container_name)( rate(container_cpu_usage_seconds_total[1m] ) )) / count(node_cpu_seconds_total{mode=\"system\"}) * 100"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes +node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "Disk",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes - container_fs_usage_bytes) / sum(container_fs_limit_bytes)"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / (node_memory_SwapTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "Available RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "title": "Node Mermory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Available Memory"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[1m])) * 100",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "Reads"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Node Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[1m])) by (id)",
     "legendFormat": "RECEIVE"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[1m])) by (id)",
     "legendFormat": "TRANSMIT"
    }
   ]
  }
 ]
}