route:
  receiver: 'slack'
  # continue: true
  # receiver: 'email'

receivers:
- name: 'slack'
  slack_configs:
  - channel: '#alertmanager'
    send_resolved: true
    text: "{{ .CommonAnnotations.description }}"
    username: 'Prometheus'
    api_url: 'https://hooks.slack.com/services/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'

# - name: 'email'
#   email_configs:
#   - to: notifications@flexigroup.com.au
#     from: alertmanager@flexigroup.com.au
#     smarthost: smtp.office365.com:587
#     auth_username: "alertmanager@flexigroup.com.au"
#     auth_password: "p@ssw0rd"
