route:
  receiver: 'slack'

receivers:
- name: 'slack'
  slack_configs:
  - channel: '#alertmanager'
    send_resolved: true
    text: "{{ .CommonAnnotations.description }}"
    username: 'Prometheus'
    api_url: 'https://hooks.slack.com/services/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'
