global:
  scrape_interval: 10s
  scrape_timeout: 10s
  external_labels:
    monitor: 'local'

rule_files:
  - 'alert.rules'

scrape_configs:

  - job_name: 'nodeexporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 10s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'test'
    scrape_interval: 10s
    metrics_path: /metrics/
    static_configs:
      - targets: ['test:5045']

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'alertmanager:9093'
