global:
  scrape_interval: 10s
  scrape_timeout: 10s
  external_labels:
    monitor: 'prod'

rule_files:
  - 'alert.rules'

scrape_configs:

  - job_name: 'nodeexporter'
    scrape_interval: 10s
    dns_sd_configs:
      - names:
          - tasks.nodeexporter
        type: A
        port: 9100

  - job_name: 'cadvisor'
    scrape_interval: 10s
    dns_sd_configs:
      - names:
          - tasks.cadvisor
        type: A
        port: 8080

  - job_name: 'prometheus'
    scrape_interval: 10s
    dns_sd_configs:
      - names:
          - tasks.prometheus
        type: A
        port: 9090

  - job_name: 'test'
    scrape_interval: 10s
    metrics_path: /metrics/
    dns_sd_configs:
      - names:
          - tasks.test
        type: A
        port: 5045

alerting:
  alertmanagers:
    - dns_sd_configs:
      - targets:
        - 'alertmanager:9093'
